import Link from "next/link";
import { ArrowRight, BadgeCheck, CalendarDays, ChevronRight, CircleAlert, Clock3, CreditCard, Download, FileText, Headphones, LockKeyhole, MoreHorizontal, PhoneCall, Plus, QrCode, Route, ShieldCheck, Sparkles, Star, TicketCheck, Users, WalletCards } from "lucide-react";
import { ActionButton } from "@/components/action-button";
import { PlatformIcon } from "@/components/platform-icon";
import { categories, getProduct, getUserModule, journey, products, userModules } from "@/lib/ecosystem";

export function AccountPage({ section = "overview" }: { section?: string }) {
  const activeModule = getUserModule(section);
  return (
    <main className="account-hub content-width">
      <header className="account-hub__head"><div><span className="eyebrow">RUVANA TRAVELER</span><h1>{activeModule.name}</h1><p>{activeModule.description}</p></div><div className="traveler-level"><span>TD</span><p><strong>Traveler Demo</strong><small><Sparkles size={13} />Explorer Gold · 12.840 poin</small></p><ChevronRight size={18} /></div></header>
      <div className="account-hub__layout"><aside className="account-sidebar"><p>TRAVELER CENTER</p><nav>{userModules.map((item) => <Link key={item.slug} className={activeModule.slug === item.slug ? "is-active" : ""} href={`/account/${item.slug}`}><PlatformIcon name={item.icon} size={18} /><span>{item.name}</span>{item.slug === "support" ? <b>2</b> : null}</Link>)}</nav><div className="account-emergency"><PhoneCall size={20} /><div><strong>Emergency 24/7</strong><small>Prioritas untuk trip aktif</small></div></div></aside><div className="account-content">{renderAccountModule(activeModule.slug)}</div></div>
    </main>
  );
}

function renderAccountModule(section: string) {
  if (section === "trips") return <TripsModule />;
  if (section === "orders") return <OrdersModule />;
  if (section === "wallet") return <WalletModule />;
  if (section === "insurance") return <InsuranceModule />;
  if (section === "rewards") return <RewardsModule />;
  if (section === "favorites") return <FavoritesModule />;
  if (section === "reviews") return <ReviewsModule />;
  if (section === "support") return <SupportModule />;
  if (section === "profile") return <ProfileModule />;
  return <AccountOverview />;
}

function AccountOverview() {
  return <>
    <section className="trip-command"><header><div><span><Route size={19} /></span><p><small>PERJALANAN AKTIF</small><strong>{journey.title}</strong><em>{journey.dates}</em></p></div><b>{journey.status}</b></header><div className="trip-command__route"><div><strong>JKT</strong><span>Jakarta</span></div><i><PlaneLine /></i><div><strong>DPS</strong><span>Denpasar</span></div></div><div className="trip-command__next"><span><Clock3 size={18} /></span><div><small>AKSI BERIKUTNYA · 19 OKT, 06.40</small><strong>Online check-in GA 402</strong><p>Data traveler dan bagasi sudah lengkap.</p></div><Link href="/account/trips">Buka perjalanan <ArrowRight size={16} /></Link></div></section>
    <div className="account-metrics"><article><WalletCards size={19} /><small>Ruvana Wallet</small><strong>Rp2.450.000</strong><span>+ Rp320.000 refund</span></article><article><TicketCheck size={19} /><small>Pesanan aktif</small><strong>6 layanan</strong><span>Semua terkonfirmasi</span></article><article><ShieldCheck size={19} /><small>Proteksi aktif</small><strong>2 polis</strong><span>Perjalanan + aktivitas</span></article><article><Star size={19} /><small>Reward points</small><strong>12.840</strong><span>Explorer Gold</span></article></div>
    <div className="account-two-column"><section className="panel"><header className="panel__header"><div><h2>Aksi penting</h2><p>Selesaikan sebelum perjalanan dimulai.</p></div></header><div className="action-checklist">{[["Lengkapi data traveler tambahan", "Dibutuhkan untuk flight dan proteksi", "profile"], ["Pilih menu penerbangan", "Tersedia sampai 18 Oktober", "orders"], ["Unduh voucher Jetski", "Tunjukkan QR saat registrasi", "orders"]].map(([title, copy, href], index) => <Link key={title} href={`/account/${href}`}><span>{index + 1}</span><p><strong>{title}</strong><small>{copy}</small></p><ChevronRight size={18} /></Link>)}</div></section><section className="panel"><header className="panel__header"><div><h2>Rekomendasi untuk trip</h2><p>Sinkron dengan lokasi dan jadwal kosong.</p></div><Link href="/explore/attraction">Lihat semua</Link></header><div className="compact-recommendations">{products.filter((item) => ["attraction", "marine", "event"].includes(item.category)).slice(0, 3).map((item) => <Link href={`/explore/${item.category}/${item.id}`} key={item.id}><span><PlatformIcon name={item.icon} size={20} /></span><p><strong>{item.title}</strong><small>{item.location}</small></p><Plus size={17} /></Link>)}</div></section></div>
  </>;
}

function TripsModule() {
  return <><section className="journey-overview"><header><div><span className="eyebrow">{journey.id}</span><h2>{journey.title}</h2><p><CalendarDays size={15} />{journey.dates} · {journey.traveler}</p></div><div><b><ShieldCheck size={15} />Protected</b><strong>{journey.total}</strong></div></header><div className="journey-progress"><span className="is-done">Booked</span><span className="is-active">Ready to go</span><span>On trip</span><span>Completed</span></div></section><section className="panel journey-timeline"><header className="panel__header"><div><h2>Itinerary terpadu</h2><p>Seluruh layanan mengikuti zona waktu lokal.</p></div><ActionButton variant="primary" message="Pencarian layanan tambahan dibuka"><Plus size={16} />Tambah layanan</ActionButton></header>{journey.items.map((item, index) => <article key={`${item.time}-${item.title}`}><div><span>{index + 1}</span><i /></div><div><small>{item.time} · {item.type}</small><strong>{item.title}</strong><p>{item.detail}</p><b>{item.status}</b></div><Link href={`/explore/${item.category}`} aria-label={`Buka ${item.title}`}><ChevronRight size={18} /></Link></article>)}</section><section className="trip-tools">{[[QrCode,"Dokumen perjalanan","6 voucher & tiket siap"],[Users,"Traveler & kontak","2 traveler · 1 emergency contact"],[WalletCards,"Ringkasan biaya",journey.total],[Headphones,"Trip support","Prioritas 24/7"]].map(([Icon,title,copy]) => <article key={title as string}><Icon size={21} /><div><strong>{title as string}</strong><span>{copy as string}</span></div><ChevronRight size={18} /></article>)}</section></>;
}

function OrdersModule() {
  const entries = [
    ["RVN-FLT-90318", "flight-cgk-dps", "20 Okt 2026", "Confirmed", "Rp3.370.000"],
    ["RVN-STY-88126", "stay-ubud", "20–24 Okt 2026", "Confirmed", "Rp7.400.000"],
    ["RVN-TRF-77310", "transfer-dps-ubud", "20 Okt 2026", "Confirmed", "Rp325.000"],
    ["RVN-MRN-66219", "marine-jetski", "23 Okt 2026", "Voucher ready", "Rp650.000"],
    ["RVN-INS-55108", "insurance-domestic", "20–24 Okt 2026", "Policy issued", "Rp90.000"],
  ];
  return <section className="panel table-panel"><header className="panel__header"><div><h2>Semua pesanan</h2><p>Tiket, voucher, booking, rental, dan polis.</p></div><div><ActionButton message="Filter pesanan dibuka">Filter</ActionButton><ActionButton variant="primary" message="Invoice gabungan disiapkan"><Download size={15} />Invoice trip</ActionButton></div></header><div className="order-filter-tabs"><button className="is-active">Semua</button><button>Mendatang</button><button>Selesai</button><button>Refund</button></div><div className="data-table"><table><thead><tr><th>Pesanan</th><th>Layanan</th><th>Tanggal</th><th>Status</th><th>Total</th><th /></tr></thead><tbody>{entries.map(([id, productId, date, status, total]) => { const product = getProduct(productId); return <tr key={id}><td><strong>{id}</strong><small>Ruvana Web</small></td><td><div className="table-service"><span><PlatformIcon name={product.icon} size={18} /></span><p><strong>{product.title}</strong><small>{product.provider}</small></p></div></td><td>{date}</td><td><span className="status">{status}</span></td><td><strong>{total}</strong></td><td><Link className="icon-action" href={`/explore/${product.category}/${product.id}`}><ChevronRight size={17} /></Link></td></tr>; })}</tbody></table></div></section>;
}

function WalletModule() {
  return <><div className="wallet-grid"><section className="wallet-card"><span>RUVANA WALLET</span><h2>Rp2.450.000</h2><p>Saldo demo tersedia</p><footer><ActionButton variant="ghost" message="Form top up dibuka">Top up</ActionButton><ActionButton variant="ghost" message="Riwayat wallet dibuka">Riwayat</ActionButton></footer></section><section className="panel wallet-summary"><h2>Simulasi pengeluaran</h2><strong>Rp12.840.500</strong><div className="spend-bars"><i style={{ width: "72%" }} /><i style={{ width: "48%" }} /><i style={{ width: "31%" }} /><i style={{ width: "18%" }} /></div><p><span>Stay 46%</span><span>Transport 31%</span><span>Experience 23%</span></p></section></div><section className="panel"><header className="panel__header"><div><h2>Metode pembayaran</h2><p>Data contoh untuk simulasi one-click checkout.</p></div><ActionButton variant="primary" message="Form tambah metode pembayaran dibuka"><Plus size={15} />Tambah</ActionButton></header><div className="payment-source-list"><article><span><CreditCard size={20} /></span><p><strong>Kartu pembayaran contoh</strong><small>Metode utama · data disamarkan</small></p><b>Utama</b><MoreHorizontal size={18} /></article><article><span><WalletCards size={20} /></span><p><strong>Akun pembayaran virtual</strong><small>Simulasi terhubung ke checkout</small></p><MoreHorizontal size={18} /></article></div></section><section className="panel table-panel"><header className="panel__header"><div><h2>Transaksi demo terbaru</h2><p>Pembayaran, refund, reward, dan adjustment sintetis.</p></div><ActionButton message="Laporan transaksi diunduh"><Download size={15} />Export</ActionButton></header><div className="finance-ledger">{[["Pembayaran Bali Escape","20 Sep 2026","- Rp8.764.000","Paid"],["Refund rental kendaraan","18 Sep 2026","+ Rp320.000","Refunded"],["Ruvana Points redemption","14 Sep 2026","- Rp125.000","Completed"]].map((row) => <div key={row[0]}><span><FileText size={18} /></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><strong>{row[2]}</strong><b>{row[3]}</b></div>)}</div></section></>;
}

function InsuranceModule() {
  return <><section className="protection-banner"><div><span><ShieldCheck size={25} /></span><p><small>PERJALANAN TERLINDUNGI</small><strong>2 polis aktif</strong><em>Bantuan darurat tersedia 24/7 selama Bali Escape.</em></p></div><ActionButton variant="ghost" message="Nomor bantuan darurat ditampilkan"><PhoneCall size={16} />Emergency line</ActionButton></section><div className="policy-list"><article className="panel"><header><div><span><ShieldCheck size={22} /></span><p><small>RVN-POL-982180</small><strong>Ruvana Protect Domestic</strong><em>Zurich Indonesia</em></p></div><b>Aktif</b></header><div><span>Periode<strong>20–24 Okt 2026</strong></span><span>Traveler<strong>2 orang</strong></span><span>Maks. manfaat<strong>Rp250 juta</strong></span></div><footer><ActionButton message="E-policy diunduh"><Download size={15} />E-policy</ActionButton><ActionButton variant="primary" message="Form klaim dibuka">Ajukan klaim</ActionButton></footer></article><article className="panel"><header><div><span><ShieldCheck size={22} /></span><p><small>RVN-ACT-66219</small><strong>Adventure Activity Cover</strong><em>Sompo Indonesia</em></p></div><b>Aktif</b></header><div><span>Aktivitas<strong>Jetski Nusa Dua</strong></span><span>Periode<strong>23 Okt 2026</strong></span><span>Maks. manfaat<strong>Rp100 juta</strong></span></div><footer><ActionButton message="E-policy diunduh"><Download size={15} />E-policy</ActionButton><ActionButton variant="primary" message="Form klaim dibuka">Ajukan klaim</ActionButton></footer></article></div><section className="panel claim-tracker"><header className="panel__header"><div><h2>Pusat klaim</h2><p>Pantau dokumen dan keputusan secara real-time.</p></div><Link href="/explore/insurance">Tambah proteksi</Link></header><div className="empty-inline"><ShieldCheck size={26} /><div><strong>Tidak ada klaim aktif</strong><span>Riwayat klaim dan dokumen akan muncul di sini.</span></div></div></section></>;
}

function RewardsModule() {
  return <><section className="reward-hero"><div><span><Sparkles size={22} />EXPLORER GOLD</span><h2>12.840 poin</h2><p>2.160 poin lagi menuju Voyager Platinum.</p><div><i style={{ width: "72%" }} /></div><small>Poin berlaku sampai 31 Desember 2027</small></div><aside><strong>5×</strong><span>Point multiplier</span><p>Untuk booking Experience sampai 30 September.</p></aside></section><div className="benefit-grid">{[["Airport lounge","2 akses tersisa","Plane"],["Priority support","Aktif 24/7","Headphones"],["Free cancellation","3 voucher","ShieldCheck"],["Member price","Diskon hingga 12%","BadgeCheck"]].map(([title,copy,icon]) => <article className="panel" key={title}><span><PlatformIcon name={icon} size={22} /></span><strong>{title}</strong><p>{copy}</p><ActionButton message={`${title} dipilih`}>Gunakan benefit</ActionButton></article>)}</div><section className="panel"><header className="panel__header"><div><h2>Tukar poin</h2><p>Gunakan untuk layanan di seluruh ekosistem.</p></div></header><div className="reward-categories">{categories.slice(0,8).map((category) => <Link href={`/explore/${category.slug}`} key={category.slug}><PlatformIcon name={category.icon} size={19} /><span>{category.short}</span><small>Mulai 500 poin</small></Link>)}</div></section></>;
}

function FavoritesModule() {
  return <section className="panel"><header className="panel__header"><div><h2>Koleksi tersimpan</h2><p>Dikelompokkan berdasarkan kebutuhan perjalanan.</p></div><ActionButton message="Koleksi baru dibuat"><Plus size={15} />Koleksi baru</ActionButton></header><div className="favorite-collections">{[["Bali October","6 item","marine-jetski"],["Family weekend","4 item","attraction-safari"],["Dream trip","8 item","aviation-heli-bali"]].map(([name,count,id]) => { const product = getProduct(id); return <Link href={`/explore/${product.category}/${product.id}`} key={name}><span><PlatformIcon name={product.icon} size={27} /></span><p><strong>{name}</strong><small>{count} · diperbarui 2 hari lalu</small></p><ChevronRight size={18} /></Link>; })}</div></section>;
}

function ReviewsModule() {
  return <><section className="review-callout"><span><Star size={24} /></span><div><strong>2 pengalaman menunggu ulasan</strong><p>Ulasan membantu traveler lain dan menjaga kualitas partner.</p></div><ActionButton variant="primary" message="Form ulasan Waterbom Bali dibuka">Tulis ulasan</ActionButton></section><section className="panel"><header className="panel__header"><div><h2>Ulasan saya</h2><p>Semua ulasan berasal dari pesanan terverifikasi.</p></div></header><div className="user-review-list">{[["Dago Forest Serviced Studio","Nyaman untuk long stay dan internetnya stabil.","4.8"],["Whoosh Jakarta → Bandung","Boarding cepat dan feeder sangat membantu.","5.0"]].map(([title,copy,rating]) => <article key={title}><header><strong>{title}</strong><span><Star size={14} fill="currentColor" />{rating}</span></header><p>{copy}</p><small>Pesanan terverifikasi · Juli 2026</small></article>)}</div></section></>;
}

function SupportModule() {
  return <><section className="support-hero"><div><span><Headphones size={25} /></span><div><small>RUVANA CARE · 24/7</small><h2>Ada yang bisa kami bantu?</h2><p>Pilih pesanan agar agen langsung melihat konteks perjalanan Anda.</p></div></div><ActionButton variant="primary" message="Chat prioritas dimulai">Mulai chat</ActionButton></section><div className="support-grid"><section className="panel"><header className="panel__header"><div><h2>Tiket aktif</h2><p>Status diperbarui real-time.</p></div></header>{[["SUP-5821","Permintaan kursi bersebelahan","Menunggu maskapai","18m"],["SUP-5798","Konfirmasi refund rental","In review","1h"]].map((row) => <Link href="/messages" key={row[0]}><span><CircleAlert size={18} /></span><p><small>{row[0]}</small><strong>{row[1]}</strong><em>{row[2]}</em></p><b>SLA {row[3]}</b><ChevronRight size={17} /></Link>)}</section><section className="panel"><header className="panel__header"><div><h2>Topik bantuan</h2><p>Jawaban cepat untuk kebutuhan umum.</p></div></header><div className="help-topics">{["Ubah jadwal atau reschedule","Pembatalan dan refund","Tiket, voucher, dan check-in","Klaim asuransi perjalanan","Kendala saat perjalanan","Keamanan akun"].map((topic) => <ActionButton key={topic} message={`Artikel ${topic} dibuka`}>{topic}<ChevronRight size={15} /></ActionButton>)}</div></section></div></>;
}

function ProfileModule() {
  return <><section className="panel profile-completion"><div><span>TD</span><p><small>PROFIL TRAVELER DEMO</small><h2>Traveler Demo</h2><em><BadgeCheck size={15} />Status simulasi terverifikasi</em></p></div><aside><strong>92%</strong><span>lengkap</span></aside></section><div className="profile-sections"><section className="panel"><header className="panel__header"><div><h2>Informasi pribadi</h2><p>Form contoh untuk data tiket dan invoice.</p></div></header><div className="form-grid"><label>Nama lengkap<input placeholder="Masukkan nama traveler" /></label><label>Email<input placeholder="Masukkan email" /></label><label>Nomor telepon<input placeholder="Masukkan nomor telepon" /></label><label>Tanggal lahir<input placeholder="Belum diisi" /></label></div><ActionButton variant="primary" message="Informasi pribadi disimpan">Simpan perubahan</ActionButton></section><section className="panel"><header className="panel__header"><div><h2>Traveler & dokumen</h2><p>Seluruh entri di bawah adalah data contoh.</p></div><ActionButton message="Form traveler baru dibuka"><Plus size={15} />Tambah</ActionButton></header><div className="traveler-list"><article><span>TD</span><p><strong>Traveler Utama Demo</strong><small>Dokumen simulasi siap</small></p><b>Utama</b><ChevronRight size={17} /></article><article><span>RT</span><p><strong>Rekan Traveler Demo</strong><small>Dokumen simulasi perlu dilengkapi</small></p><CircleAlert size={17} /><ChevronRight size={17} /></article></div></section><section className="panel"><header className="panel__header"><div><h2>Privasi & keamanan</h2><p>Lindungi akses dan transaksi akun.</p></div></header><div className="security-list"><div><LockKeyhole size={19} /><p><strong>Passkey & biometrik</strong><small>Aktif di perangkat demo</small></p><ActionButton message="Pengaturan passkey dibuka">Kelola</ActionButton></div><div><ShieldCheck size={19} /><p><strong>Verifikasi dua langkah</strong><small>Saluran verifikasi contoh</small></p><ActionButton message="Pengaturan verifikasi dibuka">Kelola</ActionButton></div></div></section></div></>;
}

function PlaneLine() {
  return <span aria-hidden="true">✦</span>;
}
