import Link from "next/link";
import { Activity, ArrowRight, BarChart3, BellRing, CalendarDays, ChevronRight, CircleAlert, Clock3, Download, FileCheck2, Filter, Globe2, MapPin, Plus, QrCode, ShieldCheck, Sparkles, TrendingUp, UserCog, Users, WalletCards, Workflow } from "lucide-react";
import { ActionButton } from "@/components/action-button";
import { PlatformIcon } from "@/components/platform-icon";
import { Metric, WorkspaceHeader } from "@/components/workspace-shell";
import { categories, getInternalModule, internalModules, partnerRoles } from "@/lib/ecosystem";

export function InternalEcosystemPage({ section }: { section: string }) {
  const activeModule = getInternalModule(section);
  return <><WorkspaceHeader eyebrow={`${activeModule.group.toUpperCase()} · NUSAVYRA HQ`} title={activeModule.name} copy={moduleDescription(activeModule.slug)} actions={<><ActionButton message={`Filter ${activeModule.name} dibuka`}><Filter size={15} />Filter</ActionButton><ActionButton variant="primary" message={`${activeModule.name} action center dibuka`}><Plus size={15} />Action center</ActionButton></>} />{renderInternalModule(activeModule.slug)}</>;
}

function moduleDescription(slug: string) {
  const descriptions: Record<string,string> = {
    partners:"Onboarding, verifikasi, performa, dan hubungan seluruh jenis partner pariwisata.", catalog:"Moderasi produk, kualitas konten, mapping kategori, harga, dan sinkronisasi supply.", orders:"Orkestrasi booking lintas stay, transportasi, attraction, event, rental, charter, dan insurance.", transport:"Pantau jadwal, manifest, delay, rute, terminal, stasiun, bandara, dan disruption transportasi.", experiences:"Kendalikan kapasitas, voucher, gate, operator, dan kualitas atraksi serta paket wisata.", events:"Pantau ticketing, venue, seat map, gate, kapasitas, promoter, dan settlement event.", fleet:"Kelola kendaraan darat, marine, dan aviation charter dalam satu operation center.", insurance:"Penerbitan polis, rule underwriting, klaim, fraud, dan emergency assistance.", settlements:"Rekonsiliasi, partner payout, reserve, komisi, pajak, dan financial exception.", finance:"Ledger, budgeting, tax, invoice, profitability, dan financial closing perusahaan.", compliance:"Perizinan, kontrak, data privacy, keselamatan, dan kewajiban regulator.", people:"Organisasi, role access, workforce planning, shift, dan produktivitas tim internal.", data:"Business intelligence lintas funnel, supply, customer, revenue, dan kualitas operasi.", system:"Kesehatan layanan, API, queue, SLA, deployment, insiden, dan integrasi partner."
  };
  return descriptions[slug] ?? "Pusat operasi lintas ekosistem Nusavyra.";
}

function renderInternalModule(slug: string) {
  if (slug === "partners") return <PartnerOperations />;
  if (slug === "catalog") return <CatalogOperations />;
  if (slug === "orders") return <OrderOrchestration />;
  if (slug === "transport") return <TransportControl />;
  if (slug === "experiences") return <ExperienceOperations />;
  if (slug === "events") return <EventOperations />;
  if (slug === "fleet") return <FleetControl />;
  if (slug === "insurance") return <InsuranceOperations />;
  if (slug === "settlements") return <SettlementOperations />;
  if (slug === "finance") return <CorporateOperations type="finance" />;
  if (slug === "compliance") return <CorporateOperations type="compliance" />;
  if (slug === "people") return <CorporateOperations type="people" />;
  if (slug === "data") return <DataIntelligence />;
  if (slug === "system") return <SystemOperations />;
  return <DataIntelligence />;
}

function PartnerOperations() {
  return <><div className="metrics metrics--four"><Metric icon={Users} label="Active partner" value="8.426" note="12 vertical bisnis" accent /><Metric icon={Clock3} label="Onboarding queue" value="184" note="Median 18 jam" /><Metric icon={ShieldCheck} label="Verified today" value="86" note="Approval 78%" /><Metric icon={CircleAlert} label="At-risk partner" value="24" note="6 high priority" /></div><section className="panel partner-supply-map"><header className="panel__header"><div><h2>Supply by ecosystem</h2><p>Ketersediaan dan kualitas per vertikal.</p></div><ActionButton message="Peta supply nasional dibuka"><Globe2 size={15} />Peta nasional</ActionButton></header><div>{partnerRoles.map((role,index) => <Link href={`/partner/${role.slug}`} key={role.slug}><span><PlatformIcon name={role.icon} size={20} /></span><p><strong>{role.name}</strong><small>{(8426-(index*421)).toLocaleString("id-ID")} partner · {index%3===0?"needs supply":"healthy"}</small></p><div className="mini-progress"><i style={{width:`${92-(index%5)*8}%`}} /></div><b>{92-(index%5)*8}%</b><ChevronRight size={17} /></Link>)}</div></section></>;
}

function CatalogOperations() {
  return <><div className="metrics metrics--four"><Metric icon={BarChart3} label="Live product" value="48.920" note="12 kategori" accent /><Metric icon={Clock3} label="Review queue" value="326" note="SLA 42 menit" /><Metric icon={ShieldCheck} label="Quality score" value="93,8%" note="↑ 1,4pt" /><Metric icon={CircleAlert} label="Price anomaly" value="42" note="Auto-held" /></div><section className="panel"><header className="panel__header"><div><h2>Catalog health</h2><p>Cakupan produk, kelengkapan, dan kesiapan booking.</p></div><ActionButton message="Bulk moderation dibuka">Bulk moderation</ActionButton></header><div className="internal-category-health">{categories.map((category,index) => <Link href={`/explore/${category.slug}`} key={category.slug}><span><PlatformIcon name={category.icon} size={19} /></span><p><strong>{category.name}</strong><small>{category.stats}</small></p><div className="mini-progress"><i style={{width:`${96-(index%4)*6}%`}} /></div><b>{index%4===3?"Attention":"Healthy"}</b></Link>)}</div></section></>;
}

function OrderOrchestration() {
  const orders=[["NSV-927-1884","Bali Escape bundle","5 services","Ready","Rp8,76 jt"],["NSV-927-1862","Jakarta–Bandung","Rail + transfer","Action needed","Rp680 rb"],["NSV-927-1848","Komodo liveaboard","Tour + flight + protect","Confirmed","Rp8,42 jt"],["NSV-927-1802","Java Jazz weekend","Event + stay","Pending payment","Rp4,86 jt"]];
  return <><div className="metrics metrics--five"><Metric icon={CalendarDays} label="Booking today" value="2.842" note="↑ 18,2%" accent /><Metric icon={Workflow} label="Multi-service trip" value="684" note="24% share" /><Metric icon={Clock3} label="Pending action" value="86" note="14 SLA risk" /><Metric icon={ShieldCheck} label="Confirmed" value="96,4%" note="Within target" /><Metric icon={WalletCards} label="Order value" value="Rp8,42 M" note="Today" /></div><section className="panel table-panel"><header className="panel__header"><div><h2>Journey orchestration queue</h2><p>Dependensi antar layanan dan aksi operasional.</p></div><ActionButton message="Orchestration rule builder dibuka">Rule builder</ActionButton></header><div className="data-table"><table><thead><tr><th>Order</th><th>Journey</th><th>Komponen</th><th>Status</th><th>Nilai</th><th /></tr></thead><tbody>{orders.map((row)=><tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td><span className="status">{row[3]}</span></td><td><strong>{row[4]}</strong></td><td><ActionButton message={`Journey ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17}/></ActionButton></td></tr>)}</tbody></table></div></section></>;
}

function TransportControl() {
  return <><section className="ops-map"><div className="map-grid"/><span className="ops-map__pin p1"><PlatformIcon name="Plane" size={15}/>28</span><span className="ops-map__pin p2"><PlatformIcon name="BusFront" size={15}/>142</span><span className="ops-map__pin p3"><PlatformIcon name="TrainFront" size={15}/>86</span><aside><small>NETWORK STATUS</small><strong>97,2% on-time</strong><p>4 delay · 1 reroute · 0 critical</p></aside></section><div className="transport-mode-grid">{[["Flight Control","286 flight","4 delayed","Plane"],["Rail Control","184 service","98,4% on-time","TrainFront"],["Bus & Shuttle","642 trip","82% load","BusFront"],["Airport Transfer","428 pickup","96% matched","CarTaxiFront"]].map((row)=><article className="panel" key={row[0]}><span><PlatformIcon name={row[3]} size={23}/></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><b>{row[2]}</b><ActionButton message={`${row[0]} dibuka`} className="icon-action"><ArrowRight size={17}/></ActionButton></article>)}</div><DisruptionQueue /> </>;
}

function DisruptionQueue() {
  return <section className="panel"><header className="panel__header"><div><h2>Disruption & recovery</h2><p>Gangguan yang berdampak pada perjalanan pelanggan.</p></div><span className="count-badge count-badge--danger">5</span></header><div className="disruption-list">{[["FLT-GA402","Delay 65 menit","184 traveler","Auto replan active","High"],["BUS-SJ182","Perubahan titik keberangkatan","28 traveler","Notification sent","Medium"],["RAIL-WH826","Feeder capacity limit","42 traveler","Alternative offered","Medium"]].map((row)=><article key={row[0]}><span><CircleAlert size={18}/></span><p><small>{row[0]}</small><strong>{row[1]}</strong><em>{row[2]} · {row[3]}</em></p><b>{row[4]}</b><ActionButton message={`Incident ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17}/></ActionButton></article>)}</div></section>;
}

function ExperienceOperations() {
  return <><div className="metrics metrics--four"><Metric icon={Users} label="Visitors today" value="42.860" note="Across 680 venues" accent /><Metric icon={CalendarDays} label="Capacity sold" value="74,2%" note="Weekend 86%" /><Metric icon={ShieldCheck} label="Voucher scanned" value="98,6%" note="Success rate" /><Metric icon={CircleAlert} label="Quality alert" value="18" note="4 high priority" /></div><section className="panel experience-control"><header className="panel__header"><div><h2>Experience live monitor</h2><p>Gate, kapasitas, visitor flow, dan operator health.</p></div><ActionButton message="Live gate monitor dibuka"><QrCode size={15}/>Gate monitor</ActionButton></header><div>{[["Taman Safari Bogor","6.842 / 8.000","86%","Normal"],["Waterbom Bali","2.184 / 2.800","78%","Normal"],["Ragunan Guided Tour","428 / 520","82%","Attention"],["Komodo National Park","184 / 200","92%","Capacity risk"]].map((row)=><article key={row[0]}><span><PlatformIcon name="FerrisWheel" size={20}/></span><p><strong>{row[0]}</strong><small>{row[1]} visitor</small></p><div className="mini-progress"><i style={{width:row[2]}}/></div><b>{row[3]}</b><ActionButton message={`${row[0]} monitor dibuka`} className="icon-action"><ChevronRight size={17}/></ActionButton></article>)}</div></section></>;
}

function EventOperations() {
  return <><div className="metrics metrics--four"><Metric icon={CalendarDays} label="Active event" value="184" note="28 this weekend" accent /><Metric icon={Users} label="Tickets sold" value="428 rb" note="Rp184 M GMV" /><Metric icon={ShieldCheck} label="Gate success" value="99,2%" note="Fraud blocked 0,08%" /><Metric icon={WalletCards} label="Settlement due" value="Rp42,8 M" note="12 promoter" /></div><div className="event-ops-grid"><section className="panel"><header className="panel__header"><div><h2>Event control room</h2><p>Event live dan mendatang.</p></div><ActionButton message="Event map dibuka">Map</ActionButton></header>{[["Java Jazz 2027","JIExpo · 28–30 Mei","68% sold","Healthy"],["Bali Marathon","Gianyar · 30 Agu","82% sold","Healthy"],["Architecture Opera","Jakarta · Feb 2027","42% sold","Setup"],["Nusantara Food Fest","Surabaya · 12 Okt","91% sold","Capacity risk"]].map((row)=><article className="event-row" key={row[0]}><span><PlatformIcon name="Ticket" size={19}/></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><em>{row[2]}</em><b>{row[3]}</b><ActionButton message={`Control room ${row[0]} dibuka`} className="icon-action"><ChevronRight size={16}/></ActionButton></article>)}</section><section className="panel"><header className="panel__header"><div><h2>Gate intelligence</h2><p>Snapshot venue aktif.</p></div><Activity size={19}/></header><div className="gate-chart"><strong>18.420</strong><span>scan / jam</span><div>{[28,44,61,78,88,72,56,82,94,68,48,32].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><footer><span>Open gates: 42</span><span>Rejected: 0,18%</span></footer></div></section></div></>;
}

function FleetControl() {
  return <><div className="fleet-overview">{[["Ground Fleet","9.240 unit","82% utilized","Car"],["Marine Fleet","780 vessel","64% utilized","ShipWheel"],["Aviation Fleet","126 aircraft","72% utilized","Helicopter"]].map((row)=><article key={row[0]}><span><PlatformIcon name={row[3]} size={26}/></span><p><small>{row[0]}</small><strong>{row[1]}</strong><em>{row[2]}</em></p><b>Operational</b></article>)}</div><section className="panel table-panel"><header className="panel__header"><div><h2>Fleet readiness</h2><p>Maintenance, crew, dokumen, dan assignment.</p></div><ActionButton message="Fleet map dibuka"><MapPin size={15}/>Live map</ActionButton></header><div className="data-table"><table><thead><tr><th>Asset</th><th>Jenis</th><th>Operator</th><th>Assignment</th><th>Readiness</th><th>Status</th><th/></tr></thead><tbody>{[["YD-HELI-08","Helicopter","Fly Bali","Scenic 14.30","98%","Ready"],["ID-YACHT-42","Yacht","Archipelago Yachts","Sunset 15.30","94%","Ready"],["B-1821-RVN","Executive Van","BaliMove","DPS pickup 10.15","86%","Inspection"],["LBJ-LIVE-12","Liveaboard","Sailing Flores","3D2N departure","100%","Boarding"]].map((row)=><tr key={row[0]}>{row.slice(0,5).map((cell,index)=><td key={cell}>{index===0?<strong>{cell}</strong>:cell}</td>)}<td><span className="status">{row[5]}</span></td><td><ActionButton message={`Asset ${row[0]} dibuka`} className="icon-action"><ChevronRight size={16}/></ActionButton></td></tr>)}</tbody></table></div></section></>;
}

function InsuranceOperations() {
  return <><div className="metrics metrics--five"><Metric icon={ShieldCheck} label="Active policy" value="184.200" note="Rp42,8 M premium" accent /><Metric icon={Clock3} label="Auto-issued" value="92,4%" note="Median 18 sec" /><Metric icon={CircleAlert} label="Open claim" value="284" note="42 priority" /><Metric icon={WalletCards} label="Claim reserve" value="Rp18,2 M" note="Loss ratio 42%" /><Metric icon={Activity} label="Assistance cases" value="18" note="2 active emergency" /></div><section className="panel insurance-queue"><header className="panel__header"><div><h2>Claim & assistance queue</h2><p>Prioritas berdasarkan keselamatan dan SLA.</p></div><ActionButton message="Underwriting rule builder dibuka">Rule builder</ActionButton></header>{[["CLM-9821","Medical assistance","Tokyo, JP","Critical","In coordination","12m"],["CLM-9818","Flight cancellation","Denpasar","High","Document review","42m"],["CLM-9812","Lost baggage","Singapore","Medium","Airline evidence","1h 18m"],["CLM-9804","Activity accident","Nusa Dua","High","Provider statement","28m"]].map((row)=><article key={row[0]}><span className={row[3]==="Critical"?"is-critical":""}><PlatformIcon name="ShieldAlert" size={19}/></span><p><small>{row[0]} · {row[2]}</small><strong>{row[1]}</strong><em>{row[4]}</em></p><b>{row[3]}</b><time>SLA {row[5]}</time><ActionButton message={`Claim ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17}/></ActionButton></article>)}</section></>;
}

function SettlementOperations() {
  return <><section className="settlement-hero"><div><small>NET SETTLEMENT TODAY</small><h2>Rp6.842.500.000</h2><p><ShieldCheck size={15}/>Reconciliation complete · difference Rp0</p></div><ActionButton variant="ghost" message="Settlement file diunduh"><Download size={15}/>Bank file</ActionButton></section><div className="metrics metrics--four"><Metric icon={WalletCards} label="Payable partner" value="Rp5,82 M" note="8.214 partner" accent/><Metric icon={Clock3} label="On hold" value="Rp128 jt" note="42 cases"/><Metric icon={TrendingUp} label="Platform revenue" value="Rp842 jt" note="Take rate 9,8%"/><Metric icon={ShieldCheck} label="Tax withheld" value="Rp52 jt" note="Posted"/></div><section className="panel"><header className="panel__header"><div><h2>Settlement batch</h2><p>Cut-off dan exception per vertical.</p></div><ActionButton message="Exception queue dibuka">Exceptions 18</ActionButton></header><div className="settlement-batches">{partnerRoles.slice(0,8).map((role,index)=><article key={role.slug}><span><PlatformIcon name={role.icon} size={18}/></span><p><strong>{role.business}</strong><small>{684-index*42} partner · Batch STL-{9270+index}</small></p><strong>Rp{(1.84-index*.12).toFixed(2)} M</strong><b>{index===3?"Review":"Ready"}</b><ActionButton message={`Batch ${role.business} dibuka`} className="icon-action"><ChevronRight size={16}/></ActionButton></article>)}</div></section></>;
}

function CorporateOperations({type}:{type:"finance"|"compliance"|"people"}) {
  if(type==="people") return <><div className="metrics metrics--four"><Metric icon={Users} label="Active employee" value="428" note="12 office & remote" accent/><Metric icon={Clock3} label="On shift" value="184" note="Operations 24/7"/><Metric icon={UserCog} label="Access review" value="18" note="Due this week"/><Metric icon={TrendingUp} label="Productivity" value="92,4%" note="↑ 2,8pt"/></div><section className="panel"><header className="panel__header"><div><h2>Workforce command</h2><p>Capacity dan coverage per operational unit.</p></div><ActionButton message="Shift planner dibuka">Shift planner</ActionButton></header><div className="workforce-grid">{internalModules.slice(1,13).map((module,index)=><article key={module.slug}><span><PlatformIcon name={module.icon} size={18}/></span><p><strong>{module.name}</strong><small>{18+index*3} anggota</small></p><div className="mini-progress"><i style={{width:`${72+(index%4)*7}%`}}/></div><b>{72+(index%4)*7}%</b></article>)}</div></section></>;
  if(type==="compliance") return <><div className="metrics metrics--four"><Metric icon={ShieldCheck} label="Compliance score" value="96,2%" note="Across ecosystem" accent/><Metric icon={FileCheck2} label="Document due" value="284" note="30 hari"/><Metric icon={CircleAlert} label="Regulatory cases" value="18" note="2 high"/><Metric icon={Clock3} label="Median closure" value="2,8 hari" note="Target < 3 hari"/></div><section className="panel compliance-program"><header className="panel__header"><div><h2>Compliance program</h2><p>Cakupan legal, safety, finance, data, dan partner.</p></div><ActionButton message="Compliance calendar dibuka">Calendar</ActionButton></header>{[["Travel business licensing","98%","12 action"],["Transport safety","94%","28 action"],["Marine & aviation certification","92%","18 action"],["Consumer protection","97%","8 action"],["Data privacy & security","99%","4 action"],["Tax & finance controls","96%","16 action"]].map((row)=><article key={row[0]}><span><FileCheck2 size={18}/></span><p><strong>{row[0]}</strong><small>{row[2]}</small></p><div className="mini-progress"><i style={{width:row[1]}}/></div><b>{row[1]}</b><ActionButton message={`${row[0]} program dibuka`} className="icon-action"><ChevronRight size={16}/></ActionButton></article>)}</section></>;
  return <><div className="metrics metrics--four"><Metric icon={WalletCards} label="Net revenue" value="Rp842 jt" note="Today" accent/><Metric icon={TrendingUp} label="Gross margin" value="28,4%" note="↑ 1,2pt"/><Metric icon={Clock3} label="Month close" value="D-3" note="92% complete"/><Metric icon={CircleAlert} label="Exception" value="18" note="Rp42,8 jt"/></div><section className="panel finance-pnl"><header className="panel__header"><div><h2>Profitability by vertical</h2><p>September 2026 · management view.</p></div><ActionButton message="P&L lengkap diunduh"><Download size={15}/>Export P&L</ActionButton></header>{partnerRoles.slice(0,9).map((role,index)=><article key={role.slug}><span><PlatformIcon name={role.icon} size={18}/></span><p><strong>{role.business}</strong><small>Revenue Rp{128-index*7},4 jt</small></p><div className="mini-progress"><i style={{width:`${84-index*4}%`}}/></div><b>{32-index}% margin</b></article>)}</section></>;
}

function DataIntelligence() {
  return <><section className="data-command"><div><span><Sparkles size={23}/></span><p><small>NUSAVYRA INTELLIGENCE</small><h2>Morning executive brief</h2><em>Demand Bali naik 18%, flight capacity turun 4%, dan marine booking berpotensi sold out akhir pekan.</em></p></div><ActionButton variant="ghost" message="Insight lengkap dibuka">Buka insight</ActionButton></section><div className="intelligence-grid">{[["Demand forecast","+14,8%","Next 14 days","TrendingUp"],["Customer LTV","Rp8,42 jt","Explorer Gold","Users"],["Supply gap","184 item","Bali & Labuan Bajo","MapPin"],["Cross-sell rate","28,6%","+4,2pt QoQ","Workflow"]].map((row)=><article className="panel" key={row[0]}><span><PlatformIcon name={row[3]} size={20}/></span><small>{row[0]}</small><strong>{row[1]}</strong><p>{row[2]}</p><div className="spark-bars">{[38,52,44,68,62,78,92].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div></article>)}</div><section className="panel"><header className="panel__header"><div><h2>Ecosystem performance</h2><p>GMV, conversion, supply, dan repeat rate.</p></div><ActionButton message="Dashboard custom builder dibuka">Customize</ActionButton></header><div className="ecosystem-performance">{categories.map((category,index)=><Link href={`/explore/${category.slug}`} key={category.slug}><span><PlatformIcon name={category.icon} size={18}/></span><p><strong>{category.short}</strong><small>Rp{(842-index*38).toLocaleString("id-ID")} jt GMV</small></p><em>{(4.8+(index%4)*.6).toFixed(1)}% CVR</em><b>{index%3===0?"↑ 18%":"↑ 8%"}</b></Link>)}</div></section></>;
}

function SystemOperations() {
  return <><section className="system-status"><div><i/><p><strong>All systems operational</strong><span>Last incident 18 days ago · 99,982% availability</span></p></div><ActionButton message="Status page publik dibuka">Public status page</ActionButton></section><div className="metrics metrics--four"><Metric icon={Activity} label="Availability" value="99,982%" note="30 days" accent/><Metric icon={Clock3} label="API latency p95" value="184 ms" note="Target < 250 ms"/><Metric icon={Workflow} label="Jobs processing" value="18.420/m" note="Queue healthy"/><Metric icon={BellRing} label="Open alert" value="3" note="0 critical"/></div><section className="panel"><header className="panel__header"><div><h2>Service health</h2><p>Core platform dan integrasi eksternal.</p></div><ActionButton message="Incident timeline dibuka">Incident history</ActionButton></header><div className="service-health-list">{[["Search & Discovery","99,99%","128 ms","Operational"],["Booking Orchestrator","99,98%","184 ms","Operational"],["Payment & Wallet","99,96%","242 ms","Degraded"],["Partner Inventory","99,99%","168 ms","Operational"],["Journey & Notification","99,97%","212 ms","Operational"],["Insurance & Claims","99,99%","196 ms","Operational"],["Data Platform","100%","4m freshness","Operational"]].map((row)=><article key={row[0]}><span className={row[3]==="Degraded"?"is-warning":""}/><p><strong>{row[0]}</strong><small>{row[1]} uptime</small></p><em>{row[2]}</em><b>{row[3]}</b><ActionButton message={`${row[0]} metrics dibuka`} className="icon-action"><ChevronRight size={16}/></ActionButton></article>)}</div></section></>;
}
