import Link from "next/link";
import { CalendarDays, ChevronRight, Download, Filter, MessageSquare, Settings, ShieldCheck, UserRound, WalletCards } from "lucide-react";
import { ActionButton } from "@/components/action-button";
import { StatusPill } from "@/components/status-pill";
import { Metric, WorkspaceHeader } from "@/components/workspace-shell";

const reservations = [
  ["NSV-DEMO-A", "Traveler Demo A", "Verde Sky Loft", "20–23 Sep", "Confirmed", "Rp2,83 jt"],
  ["NSV-DEMO-B", "Traveler Demo B", "Ubud Riverstone", "2–5 Okt", "Pending", "Rp6,03 jt"],
  ["NSV-DEMO-C", "Traveler Demo C", "Dago Forest", "14 Okt–14 Nov", "Confirmed", "Rp7,42 jt"],
  ["NSV-DEMO-D", "Traveler Demo D", "Verde Sky Loft", "21–24 Nov", "Review", "Rp3,15 jt"],
];

export function OwnerReservationsSkyPage() {
  return <><WorkspaceHeader eyebrow="RESERVATION CLOUD · DEMO" title="Reservasi" copy="Pantau permintaan, check-in, masa tinggal, dan check-out dari satu command center." actions={<ActionButton message="Data reservasi demo disiapkan"><Download size={16} />Ekspor data</ActionButton>} /><div className="metrics metrics--four"><Metric icon={CalendarDays} label="Booking aktif" value="47" note="Data simulasi" accent /><Metric icon={ShieldCheck} label="Check-in siap" value="6" note="Semua PIC assigned" /><Metric icon={MessageSquare} label="Perlu respons" value="3" note="SLA terdekat 18 menit" /><Metric icon={WalletCards} label="Nilai booking" value="Rp128 jt" note="Simulasi bulan berjalan" /></div><section className="panel table-panel"><header className="panel__header"><div><h2>Reservasi demo</h2><p>Seluruh nama dan referensi adalah data sintetis.</p></div><ActionButton message="Filter reservasi dibuka"><Filter size={15} />Filter</ActionButton></header><div className="data-table"><table><thead><tr><th>Booking</th><th>Traveler</th><th>Properti</th><th>Periode</th><th>Status</th><th>Nilai</th><th /></tr></thead><tbody>{reservations.map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><StatusPill>{row[4]}</StatusPill></td><td><strong>{row[5]}</strong></td><td><Link className="icon-action" href="/account/orders" aria-label={`Buka ${row[0]}`}><ChevronRight size={17} /></Link></td></tr>)}</tbody></table></div></section></>;
}

export function OwnerFinanceSkyPage() {
  const ledger = [["DEMO-REVENUE-A","Pendapatan booking","+ Rp18.720.000","Cleared"],["DEMO-FEE-B","Biaya platform","- Rp1.872.000","Posted"],["DEMO-PAYOUT-C","Payout terjadwal","- Rp12.800.000","Scheduled"],["DEMO-REFUND-D","Refund pelanggan","- Rp820.000","Completed"]];
  return <><WorkspaceHeader eyebrow="FINANCE CLOUD · DEMO" title="Keuangan" copy="Saldo, escrow, settlement, invoice, dan payout dengan data simulasi yang aman." actions={<ActionButton message="Laporan keuangan demo disiapkan"><Download size={16} />Unduh laporan</ActionButton>} /><section className="finance-hero"><div><small>SALDO SIMULASI TERSEDIA</small><h2>Rp18.420.000</h2><p><ShieldCheck size={15} />Akun payout demo · data disamarkan</p></div><ActionButton variant="ghost" message="Rincian payout dibuka">Rincian payout</ActionButton></section><div className="module-stats"><article><small>Gross booking value</small><strong>Rp86,4 jt</strong><span>Data demo</span></article><article><small>Dalam escrow</small><strong>Rp6,44 jt</strong><span>4 booking aktif</span></article><article><small>Platform fee</small><strong>Rp8,64 jt</strong><span>Rata-rata 10%</span></article><article><small>Payout berikutnya</small><strong>Rp24,86 jt</strong><span>Jadwal simulasi</span></article></div><section className="panel"><header className="panel__header"><div><h2>Ledger simulasi</h2><p>Tidak memuat rekening atau transaksi nyata.</p></div><ActionButton message="Filter ledger dibuka"><Filter size={15} />Filter</ActionButton></header><div className="finance-ledger">{ledger.map((row) => <div key={row[0]}><span><WalletCards size={18} /></span><p><small>{row[0]}</small><strong>{row[1]}</strong></p><strong>{row[2]}</strong><b>{row[3]}</b></div>)}</div></section></>;
}

export function OwnerInboxSkyPage() {
  const threads = [["TA","Traveler Demo A","Pertanyaan early check-in","2m"],["TB","Traveler Demo B","Airport transfer tersedia?","12m"],["OP","Operator Demo","Housekeeping selesai","28m"]];
  return <><WorkspaceHeader eyebrow="UNIFIED INBOX" title="Inbox partner" copy="Percakapan traveler, vendor, dan Nusavyra Care dalam satu ruang kerja." actions={<ActionButton variant="primary" message="Percakapan baru dibuka"><MessageSquare size={16} />Pesan baru</ActionButton>} /><section className="partner-inbox panel"><aside>{threads.map((row,index) => <button className={index === 0 ? "is-active" : ""} key={row[1]}><span>{row[0]}</span><p><strong>{row[1]}</strong><small>Data percakapan simulasi</small><em>{row[2]}</em></p><time>{row[3]}</time></button>)}</aside><div className="partner-chat"><header><span>TA</span><p><strong>Traveler Demo A</strong><small>Reservasi simulasi · check-in hari ini</small></p><ActionButton message="Detail reservasi dibuka">Detail</ActionButton></header><div><p className="is-guest">Apakah saya dapat datang sedikit lebih awal?<small>18.31</small></p><p className="is-partner">Tentu. Area tunggu sudah siap dan tim operasional telah mendapat notifikasi.<small>18.33 · Read</small></p></div><footer><ActionButton message="Lampiran dipilih">+</ActionButton><input placeholder="Tulis balasan..." /><ActionButton variant="primary" message="Pesan simulasi terkirim">Kirim</ActionButton></footer></div></section></>;
}

export function OwnerSettingsSkyPage() {
  return <><WorkspaceHeader eyebrow="BUSINESS SETTINGS" title="Pengaturan bisnis" copy="Atur profil, payout, tim, notifikasi, keamanan, dan integrasi workspace." /><div className="partner-settings"><section className="panel"><header className="panel__header"><div><h2>Profil bisnis demo</h2><p>Gunakan data perusahaan saat backend resmi diaktifkan.</p></div><UserRound size={20} /></header><div className="form-grid"><label>Nama bisnis<input placeholder="Masukkan nama bisnis" /></label><label>Jenis pemilik<select defaultValue="company"><option value="company">Badan usaha</option><option value="personal">Perorangan</option></select></label><label>Email operasional<input placeholder="Masukkan email operasional" /></label><label>Nomor bantuan<input placeholder="Masukkan nomor bantuan" /></label><label className="form-grid__full">Alamat bisnis<textarea placeholder="Masukkan alamat bisnis" /></label></div><ActionButton variant="primary" message="Profil bisnis demo disimpan">Simpan profil</ActionButton></section><section className="panel"><header className="panel__header"><div><h2>Keamanan & preferensi</h2><p>Kontrol hak akses dan notifikasi operasional.</p></div><Settings size={20} /></header><div className="settings-cards"><button><strong>Verifikasi dua langkah</strong><span>Aktif untuk seluruh administrator</span><ShieldCheck size={17} /></button><button><strong>Role & permission</strong><span>4 role workspace aktif</span><ChevronRight size={17} /></button><button><strong>Integrasi payout</strong><span>Belum dikonfigurasi dalam mode demo</span><ChevronRight size={17} /></button></div></section></div></>;
}
