import Link from "next/link";
import { BarChart3, CalendarDays, Check, ChevronDown, ChevronRight, Clock3, Download, FileCheck2, Filter, Headphones, Link2, MoreHorizontal, Plus, Search, ShieldCheck, Sparkles, Star, TrendingUp, UserPlus, WalletCards, Workflow } from "lucide-react";
import { ActionButton } from "@/components/action-button";
import { PlatformIcon } from "@/components/platform-icon";
import { getPartnerModule, getPartnerRole, partnerModules, partnerRoles } from "@/lib/ecosystem";

export function PartnerPage({ roleSlug, section = "dashboard" }: { roleSlug: string; section?: string }) {
  const role = getPartnerRole(roleSlug);
  const activeModule = getPartnerModule(section);
  return (
    <main className="partner-portal">
      <aside className="partner-sidebar">
        <div className="partner-identity"><span><PlatformIcon name={role.icon} size={21} /></span><p><small>{role.business}</small><strong>{role.name}</strong></p><details><summary aria-label="Ganti bisnis"><ChevronDown size={16} /></summary><div>{partnerRoles.map((item) => <Link key={item.slug} href={`/partner/${item.slug}`}><PlatformIcon name={item.icon} size={17} /><span><strong>{item.name}</strong><small>{item.business}</small></span>{item.slug === role.slug ? <Check size={15} /> : null}</Link>)}</div></details></div>
        <p>PARTNER WORKSPACE</p><nav>{partnerModules.map((item) => <Link key={item.slug} className={activeModule.slug === item.slug ? "is-active" : ""} href={`/partner/${role.slug}/${item.slug}`}><PlatformIcon name={item.icon} size={18} /><span>{item.name}</span>{item.slug === "inbox" ? <b>4</b> : null}</Link>)}</nav>
        <div className="partner-health"><ShieldCheck size={19} /><p><strong>Akun terverifikasi</strong><small>Compliance score 96%</small></p></div>
      </aside>
      <div className="partner-main"><header className="partner-heading"><div><span className="eyebrow">{role.business.toUpperCase()} · {activeModule.name.toUpperCase()}</span><h1>{activeModule.slug === "dashboard" ? `Selamat malam, ${role.name}` : activeModule.name}</h1><p>{moduleCopy(activeModule.slug, role.name)}</p></div><div><ActionButton message="Pusat bantuan partner dibuka"><Headphones size={16} />Bantuan</ActionButton><ActionButton variant="primary" message={primaryAction(activeModule.slug)}><Plus size={16} />{primaryLabel(activeModule.slug)}</ActionButton></div></header>{renderPartnerModule(activeModule.slug, role)}</div>
    </main>
  );
}

function moduleCopy(section: string, role: string) {
  const copy: Record<string, string> = {
    dashboard: `Pantau performa ${role.toLowerCase()}, operasional, dan peluang hari ini.`, catalog: "Kelola layanan, variasi, harga, kapasitas, dan status publikasi.", bookings: "Tangani pesanan lintas channel dari konfirmasi sampai layanan selesai.", schedule: "Atur ketersediaan, kapasitas, blackout, dan alokasi channel.", operations: "Koordinasikan tugas lapangan, SLA, insiden, dan serah-terima.", customers: "Kenali tamu, preferensi, riwayat, dan komunikasi yang relevan.", finance: "Pantau pendapatan, refund, biaya, pajak, dan payout partner.", marketing: "Kelola promo, channel distribusi, campaign, dan performa akuisisi.", reviews: "Tanggapi ulasan, pantau kualitas, dan tindak lanjuti service recovery.", reports: "Analisis performa komersial, operasional, dan kualitas layanan.", team: "Atur anggota tim, role, cabang, shift, dan hak akses.", compliance: "Lengkapi legalitas, sertifikasi, perizinan, dan dokumen keselamatan.", inbox: "Pesan pelanggan dan koordinasi dengan tim Ruvana dalam satu inbox.", settings: "Konfigurasi profil bisnis, integrasi, kebijakan, dan notifikasi."
  };
  return copy[section] ?? copy.dashboard;
}

function primaryLabel(section: string) {
  const labels: Record<string, string> = { dashboard: "Quick action", catalog: "Tambah produk", bookings: "Booking manual", schedule: "Blok jadwal", operations: "Buat tugas", customers: "Tambah pelanggan", finance: "Tarik saldo", marketing: "Buat campaign", reviews: "Minta ulasan", reports: "Buat laporan", team: "Undang anggota", compliance: "Upload dokumen", inbox: "Pesan baru", settings: "Simpan konfigurasi" };
  return labels[section] ?? "Tambah data";
}

function primaryAction(section: string) {
  return `${primaryLabel(section)} dibuka untuk diisi`;
}

type Role = ReturnType<typeof getPartnerRole>;

function renderPartnerModule(section: string, role: Role) {
  if (section === "catalog") return <PartnerCatalog role={role} />;
  if (section === "bookings") return <PartnerBookings role={role} />;
  if (section === "schedule") return <PartnerSchedule role={role} />;
  if (section === "operations") return <PartnerOperations role={role} />;
  if (section === "customers") return <PartnerCustomers />;
  if (section === "finance") return <PartnerFinance />;
  if (section === "marketing") return <PartnerMarketing />;
  if (section === "reviews") return <PartnerReviews />;
  if (section === "reports") return <PartnerReports role={role} />;
  if (section === "team") return <PartnerTeam />;
  if (section === "compliance") return <PartnerCompliance role={role} />;
  if (section === "inbox") return <PartnerInbox />;
  if (section === "settings") return <PartnerSettings role={role} />;
  return <PartnerDashboard role={role} />;
}

function PartnerDashboard({ role }: { role: Role }) {
  return <><div className="partner-kpis">{role.kpi.map((kpi, index) => { const [value, ...labelParts] = kpi.split(" "); return <article key={kpi} className={index === 0 ? "is-accent" : ""}><span><PlatformIcon name={["TrendingUp", "WalletCards", "Star"][index] ?? "Activity"} size={18} /></span><small>{labelParts.join(" ") || "Performa"}</small><strong>{value}</strong><p>{index === 0 ? "↑ 8,4% periode sebelumnya" : index === 1 ? "Target tercapai 82%" : "Di atas standar Ruvana"}</p></article>; })}<article><span><CalendarDays size={18} /></span><small>Booking aktif</small><strong>128</strong><p>24 layanan hari ini</p></article></div>
    <section className="partner-alert"><div><span><Sparkles size={20} /></span><p><strong>Peluang optimasi ditemukan</strong><small>Permintaan akhir pekan naik 24%. Buka kapasitas tambahan dan aktifkan harga dinamis.</small></p></div><ActionButton message="Rekomendasi harga dan kapasitas diterapkan">Terapkan rekomendasi</ActionButton></section>
    <div className="partner-dashboard-grid"><section className="panel"><header className="panel__header"><div><h2>Operasional hari ini</h2><p>27 September 2026 · zona waktu lokal</p></div><Link href={`/partner/${role.slug}/operations`}>Buka operasi</Link></header><div className="today-operations">{[["07.30","Persiapan layanan pertama","Tim lapangan","Ready"],["10.15","Kedatangan / check-in","4 pelanggan","On schedule"],["13.00","Pemeriksaan kapasitas","Ops lead","Action needed"],["17.30","Closing & reconciliation","Finance","Scheduled"]].map((row) => <article key={row[0]}><time>{row[0]}</time><span /><p><strong>{row[1]}</strong><small>{row[2]}</small></p><b>{row[3]}</b></article>)}</div></section><section className="panel"><header className="panel__header"><div><h2>Health monitor</h2><p>Kesiapan layanan dan integrasi.</p></div><ShieldCheck size={20} /></header><div className="health-score"><strong>94</strong><span>/100</span><p>Excellent</p></div><div className="health-list">{[[role.inventoryLabel,"96% siap"],[role.scheduleLabel,"Sinkron"],[role.operationsLabel,"2 perhatian"],["Pembayaran & payout","Normal"]].map(([label,value],index) => <div key={label}><span className={index === 2 ? "is-warning" : ""} /><p>{label}</p><strong>{value}</strong></div>)}</div></section></div>
    <section className="panel ecosystem-connections"><header className="panel__header"><div><h2>Terhubung ke ekosistem</h2><p>Cross-sell aktif meningkatkan nilai setiap perjalanan.</p></div><ActionButton message="Pengaturan bundling dibuka">Kelola koneksi</ActionButton></header><div>{[["Ruvana Journey","Masuk otomatis ke itinerary pelanggan","Route"],["Ruvana Pay","Pembayaran, refund, dan payout","WalletCards"],["Ruvana Protect","Proteksi transaksi dan aktivitas","ShieldCheck"],["Ruvana Care","Dukungan dan pusat resolusi 24/7","Headphones"],["Ruvana Rewards","Poin dan benefit member","Gift"]].map(([title,copy,icon]) => <article key={title}><span><PlatformIcon name={icon} size={20} /></span><p><strong>{title}</strong><small>{copy}</small></p><b>Aktif</b></article>)}</div></section>
  </>;
}

function PartnerCatalog({ role }: { role: Role }) {
  const rows = [["PRD-001","Paket Utama Premium","Live","82%","Rp18,4 jt"],["PRD-002","Pilihan Standard","Live","64%","Rp12,8 jt"],["PRD-003","Private / Exclusive","Review","—","Rp8,2 jt"],["PRD-004","Group & Corporate","Draft","—","—"]];
  return <><div className="module-stats"><article><small>Total {role.inventoryLabel}</small><strong>42</strong><span>36 live</span></article><article><small>Kapasitas terjual</small><strong>78%</strong><span>7 hari ke depan</span></article><article><small>Completeness</small><strong>94%</strong><span>2 item perlu foto</span></article><article><small>Channel aktif</small><strong>6</strong><span>Semua sinkron</span></article></div><section className="panel table-panel"><header className="panel__header"><div><h2>{role.inventoryLabel}</h2><p>Kelola konten, harga, status, dan ketersediaan.</p></div><div><ActionButton message="Filter katalog dibuka"><Filter size={15} />Filter</ActionButton><ActionButton message="Bulk editor dibuka">Bulk edit</ActionButton></div></header><div className="catalog-tabs"><button className="is-active">Semua 42</button><button>Live 36</button><button>Review 3</button><button>Draft 3</button></div><div className="data-table"><table><thead><tr><th>ID & produk</th><th>Status</th><th>Utilisasi</th><th>GMV 30 hari</th><th>Kelengkapan</th><th /></tr></thead><tbody>{rows.map((row,index) => <tr key={row[0]}><td><div className="table-service"><span><PlatformIcon name={role.icon} size={18} /></span><p><strong>{row[1]}</strong><small>{row[0]} · diperbarui {index + 1} jam lalu</small></p></div></td><td><span className="status">{row[2]}</span></td><td>{row[3]}</td><td><strong>{row[4]}</strong></td><td><div className="mini-progress"><i style={{ width: `${96-index*9}%` }} /></div></td><td><ActionButton message={`Editor ${row[1]} dibuka`} className="icon-action"><ChevronRight size={17} /></ActionButton></td></tr>)}</tbody></table></div></section></>;
}

function PartnerBookings({ role }: { role: Role }) {
  const rows = [["DEMO-ORDER-A","Traveler Demo A","Hari ini · 10.15","Confirmed","Rp2.850.000"],["DEMO-ORDER-B","Traveler Demo B","Hari ini · 13.00","Action needed","Rp1.420.000"],["DEMO-ORDER-C","Traveler Demo C","Besok · 08.30","Confirmed","Rp4.880.000"],["DEMO-ORDER-D","Traveler Demo D","29 Sep · 15.30","Pending payment","Rp925.000"]];
  return <><section className="booking-command panel"><header><div><strong>128</strong><span>Booking aktif</span></div><div><strong>24</strong><span>Hari ini</span></div><div><strong>4</strong><span>Perlu tindakan</span></div><div><strong>96%</strong><span>Acceptance rate</span></div></header><div><Search size={18} /><input placeholder="Cari booking, nama pelanggan, atau kode voucher" /><ActionButton message="Filter lanjutan dibuka"><Filter size={15} />Filter</ActionButton></div></section><section className="panel table-panel"><header className="panel__header"><div><h2>Booking & pesanan</h2><p>{role.business} · seluruh channel penjualan.</p></div><ActionButton message="Manifest hari ini diunduh"><Download size={15} />Manifest</ActionButton></header><div className="data-table"><table><thead><tr><th>Booking</th><th>Pelanggan</th><th>Jadwal</th><th>Status</th><th>Nilai</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td><strong>{row[0]}</strong><small>Ruvana App</small></td><td>{row[1]}</td><td>{row[2]}</td><td><span className="status">{row[3]}</span></td><td><strong>{row[4]}</strong></td><td><ActionButton message={`Detail ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17} /></ActionButton></td></tr>)}</tbody></table></div></section></>;
}

function PartnerSchedule({ role }: { role: Role }) {
  const days = ["Sen 28","Sel 29","Rab 30","Kam 1","Jum 2","Sab 3","Min 4"];
  return <><section className="panel schedule-toolbar"><div><ActionButton message="Minggu sebelumnya dibuka">←</ActionButton><h2>28 Sep – 4 Okt 2026</h2><ActionButton message="Minggu berikutnya dibuka">→</ActionButton></div><div><span><i className="available" />Tersedia</span><span><i className="booked" />Terisi</span><span><i className="blocked" />Diblokir</span></div></section><section className="panel capacity-calendar"><div className="capacity-calendar__head"><strong>{role.scheduleLabel}</strong>{days.map((day) => <span key={day}>{day}</span>)}</div>{["Premium","Standard","Private","Group"].map((item,rowIndex) => <div className="capacity-calendar__row" key={item}><p><strong>{item}</strong><small>Inventory #{rowIndex+1}</small></p>{days.map((day,index) => <ActionButton key={day} message={`${item} · ${day} dipilih`} className={(index+rowIndex)%5===0?"is-blocked":(index+rowIndex)%3===0?"is-booked":""}><strong>{(index+2)*(rowIndex+3)}</strong><small>{(index+rowIndex)%5===0?"Block":(index+rowIndex)%3===0?"Full":"slot"}</small></ActionButton>)}</div>)}</section><section className="calendar-summary"><article><Clock3 size={20} /><p><strong>Cut-off otomatis</strong><small>Booking ditutup 2 jam sebelum layanan.</small></p><b>Aktif</b></article><article><Link2 size={20} /><p><strong>Channel sync</strong><small>6 channel terakhir sinkron 3 menit lalu.</small></p><b>Normal</b></article><article><TrendingUp size={20} /><p><strong>Smart allocation</strong><small>20% kapasitas dijaga untuk direct booking.</small></p><b>Aktif</b></article></section></>;
}

function PartnerOperations({ role }: { role: Role }) {
  const columns = [{ title:"Baru",items:[["OPS-842","Persiapan layanan premium","High"],["OPS-839","Validasi passenger list","Medium"]]},{title:"Ditugaskan",items:[["OPS-834",role.operationsLabel,"High"],["OPS-829","Konfirmasi vendor pendukung","Medium"]]},{title:"Dikerjakan",items:[["OPS-820","Quality inspection","Medium"],["OPS-818","Customer special request","High"]]},{title:"Selesai",items:[["OPS-812","Closing layanan #1801","Completed"],["OPS-809","Daily safety check","Completed"]]}];
  return <><div className="operations-banner"><div><Workflow size={24} /><p><strong>{role.operationsLabel}</strong><small>2 tugas berisiko melewati SLA · 1 insiden perlu review.</small></p></div><ActionButton variant="ghost" message="Pusat insiden dibuka">Incident center</ActionButton></div><section className="partner-kanban">{columns.map((column) => <div key={column.title}><header><strong>{column.title}</strong><span>{column.items.length}</span></header>{column.items.map((item) => <article key={item[0]}><small>{item[0]}</small><strong>{item[1]}</strong><p><Clock3 size={13} />Due {item[0]==="OPS-842"?"45 menit":"hari ini"}</p><footer><span className={item[2]==="High"?"is-high":""}>{item[2]}</span><ActionButton message={`Detail ${item[0]} dibuka`} className="icon-action"><MoreHorizontal size={16} /></ActionButton></footer></article>)}</div>)}</section></>;
}

function PartnerCustomers() {
  return <><div className="module-stats"><article><small>Total pelanggan</small><strong>3.842</strong><span>+12% QoQ</span></article><article><small>Repeat rate</small><strong>31,8%</strong><span>↑ 3,2pt</span></article><article><small>Rata-rata nilai</small><strong>Rp1,84 jt</strong><span>Per booking</span></article><article><small>Gold member</small><strong>428</strong><span>High-value</span></article></div><section className="panel"><header className="panel__header"><div><h2>Customer intelligence</h2><p>Segmentasi berbasis izin dan perilaku transaksi.</p></div><ActionButton message="Segment builder dibuka">Buat segmen</ActionButton></header><div className="customer-segments">{[["High-value traveler","428 pelanggan","Rp4,8 jt avg.","#0b7f72"],["Family explorer","1.204 pelanggan","2,8 booking/tahun","#246bfd"],["Business frequent","684 pelanggan","42% repeat","#7b5ce7"],["At-risk customer","96 pelanggan","Perlu re-engagement","#d1495b"]].map((row) => <article key={row[0]}><i style={{ background: row[3] }} /><strong>{row[0]}</strong><p>{row[1]}</p><span>{row[2]}</span><ActionButton message={`Segmen ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17} /></ActionButton></article>)}</div></section></>;
}

function PartnerFinance() {
  return <><section className="finance-hero"><div><small>SALDO SIMULASI</small><h2>Rp184.520.000</h2><p><ShieldCheck size={15} />Akun pencairan demo · data disamarkan</p></div><ActionButton variant="ghost" message="Form tarik saldo dibuka">Tarik saldo</ActionButton></section><div className="module-stats"><article><small>Gross booking value</small><strong>Rp428,4 jt</strong><span>Data demo bulan ini</span></article><article><small>Net revenue</small><strong>Rp384,9 jt</strong><span>Setelah fee</span></article><article><small>Refund</small><strong>Rp8,2 jt</strong><span>1,9% dari GMV</span></article><article><small>Payout berikutnya</small><strong>Rp92,8 jt</strong><span>Jadwal simulasi</span></article></div><section className="panel table-panel"><header className="panel__header"><div><h2>Settlement & transaksi demo</h2><p>Simulasi rekonsiliasi otomatis lintas metode pembayaran.</p></div><ActionButton message="Laporan settlement diunduh"><Download size={15} />Export</ActionButton></header><div className="finance-ledger">{[["DEMO-SETTLEMENT-A","Settlement mingguan","+ Rp92.840.000","Scheduled"],["DEMO-REFUND-B","Refund pesanan contoh","- Rp1.420.000","Completed"],["DEMO-FEE-C","Platform & payment fee","- Rp8.285.000","Posted"],["DEMO-REVENUE-D","Booking revenue","+ Rp18.720.000","Cleared"]].map((row) => <div key={row[0]}><span><WalletCards size={18} /></span><p><small>{row[0]}</small><strong>{row[1]}</strong></p><strong>{row[2]}</strong><b>{row[3]}</b></div>)}</div></section></>;
}

function PartnerMarketing() {
  return <><div className="module-stats"><article><small>Attributed GMV</small><strong>Rp286 jt</strong><span>ROAS 5,2×</span></article><article><small>Impression</small><strong>842 rb</strong><span>+24% MoM</span></article><article><small>Conversion</small><strong>4,8%</strong><span>↑ 0,6pt</span></article><article><small>Voucher used</small><strong>1.284</strong><span>31% repeat</span></article></div><div className="campaign-workspace"><section className="panel"><header className="panel__header"><div><h2>Campaign aktif</h2><p>Direct, affiliate, dan paid channel.</p></div><Link href="#channels">Lihat channel</Link></header>{[["Weekend Explorer","Ruvana App + Meta","Rp82 jt","6,4×","78%"],["Family Holiday","Search + CRM","Rp64 jt","4,9×","62%"],["Last Minute Deal","Ruvana App","Rp38 jt","7,1×","44%"]].map((row) => <article className="campaign-row" key={row[0]}><span><Sparkles size={18} /></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><div><small>Revenue</small><strong>{row[2]}</strong></div><div><small>ROAS</small><strong>{row[3]}</strong></div><div className="mini-progress"><i style={{ width: row[4] }} /></div><ActionButton message={`Campaign ${row[0]} dibuka`} className="icon-action"><ChevronRight size={17} /></ActionButton></article>)}</section><section className="panel" id="channels"><header className="panel__header"><div><h2>Distribution health</h2><p>Status integrasi dan harga.</p></div></header><div className="channel-health">{[["Ruvana Direct","Live","100%"],["Google Things to do","Live","96%"],["Meta Travel Ads","Live","88%"],["Affiliate Network","Attention","72%"]].map((row) => <div key={row[0]}><span><Link2 size={17} /></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><div className="mini-progress"><i style={{ width: row[2] }} /></div><b>{row[2]}</b></div>)}</div></section></div></>;
}

function PartnerReviews() {
  return <><section className="review-overview panel"><div><small>RATING SIMULASI</small><strong>4,91</strong><span><Star size={18} fill="currentColor" /><Star size={18} fill="currentColor" /><Star size={18} fill="currentColor" /><Star size={18} fill="currentColor" /><Star size={18} fill="currentColor" /></span><p>1.284 ulasan demo</p></div><aside>{[[5,82],[4,13],[3,3],[2,1],[1,1]].map(([rating,value]) => <div key={rating}><span>{rating}</span><Star size={12} /><i><b style={{ width: `${value}%` }} /></i><strong>{value}%</strong></div>)}</aside></section><section className="panel"><header className="panel__header"><div><h2>Ulasan demo terbaru</h2><p>Simulasi respons publik dan service recovery.</p></div><ActionButton message="Filter sentimen dibuka"><Filter size={15} />Filter</ActionButton></header><div className="partner-review-list">{[["Traveler Demo A","5.0","Pelayanan cepat dan semua informasi sangat jelas.","Belum dibalas"],["Traveler Demo B","4.6","Secara keseluruhan baik, titik temu perlu dibuat lebih jelas.","Perlu tindak lanjut"],["Traveler Demo C","5.0","Proses dari booking sampai selesai sangat mulus.","Sudah dibalas"]].map((row) => <article key={row[0]}><header><span>{row[0].split(" ").map((v)=>v[0]).join("")}</span><p><strong>{row[0]}</strong><small>Pesanan simulasi · 2 hari lalu</small></p><b><Star size={13} fill="currentColor" />{row[1]}</b></header><p>{row[2]}</p><footer><em>{row[3]}</em><ActionButton message={`Kotak balasan untuk ${row[0]} dibuka`}>Balas ulasan</ActionButton></footer></article>)}</div></section></>;
}

function PartnerReports({ role }: { role: Role }) {
  return <><section className="report-builder panel"><div><span><BarChart3 size={24} /></span><p><strong>Executive performance report</strong><small>Ringkasan komersial, operasional, dan kualitas · September 2026</small></p></div><ActionButton message="PDF executive report diunduh"><Download size={16} />Download PDF</ActionButton></section><div className="report-grid">{[["Revenue trend","Rp428,4 jt","+12,8%",[42,58,51,66,72,68,84]],["Utilization","78,4%","+5,2pt",[52,48,64,72,68,78,86]],["Average order","Rp1,84 jt","+8,1%",[32,46,48,54,62,58,71]],["Service quality","4,91","+0,08",[78,82,81,86,88,91,94]]].map((item) => <article className="panel" key={item[0] as string}><header><div><small>{item[0] as string}</small><strong>{item[1] as string}</strong></div><b>{item[2] as string}</b></header><div className="micro-chart">{(item[3] as number[]).map((value,index) => <i key={index} style={{ height: `${value}%` }} />)}</div><footer><span>24 Sep</span><span>Hari ini</span></footer></article>)}</div><section className="panel"><header className="panel__header"><div><h2>Laporan terjadwal</h2><p>Dikirim otomatis ke pemilik dan finance.</p></div><ActionButton message="Report scheduler dibuka">Atur jadwal</ActionButton></header><div className="scheduled-reports">{[["Daily operations",role.operationsLabel,"Setiap 20.00"],["Weekly commercial","GMV, conversion, channel","Setiap Senin"],["Monthly owner statement","Revenue, fee, payout","Tanggal 1"]].map((row) => <div key={row[0]}><FileCheck2 size={19} /><p><strong>{row[0]}</strong><small>{row[1]}</small></p><span>{row[2]}</span><b>Aktif</b></div>)}</div></section></>;
}

function PartnerTeam() {
  return <><div className="module-stats"><article><small>Anggota demo aktif</small><strong>24</strong><span>4 cabang</span></article><article><small>On shift</small><strong>12</strong><span>Hari ini</span></article><article><small>Pending invite</small><strong>3</strong><span>Perlu follow-up</span></article><article><small>Access review</small><strong>2</strong><span>Jatuh tempo</span></article></div><section className="panel table-panel"><header className="panel__header"><div><h2>Tim & hak akses demo</h2><p>Role-based access untuk setiap unit dan cabang.</p></div><ActionButton variant="primary" message="Form undang anggota dibuka"><UserPlus size={15} />Undang</ActionButton></header><div className="data-table"><table><thead><tr><th>Anggota</th><th>Role</th><th>Cakupan</th><th>Shift</th><th>Status</th><th /></tr></thead><tbody>{[["Operator Demo A","Operations Manager","Semua cabang","08.00–17.00","Active"],["Operator Demo B","Finance","HQ","09.00–18.00","Active"],["Operator Demo C","Field Operations","Cabang Bali","07.00–16.00","On shift"],["Operator Demo D","Customer Service","Remote","14.00–23.00","On shift"]].map((row) => <tr key={row[0]}><td><div className="team-member"><span>{row[0].split(" ").map((v)=>v[0]).join("")}</span><strong>{row[0]}</strong></div></td><td>{row[1]}</td><td>{row[2]}</td><td>{row[3]}</td><td><span className="status">{row[4]}</span></td><td><ActionButton message={`Hak akses ${row[0]} dibuka`} className="icon-action"><MoreHorizontal size={17} /></ActionButton></td></tr>)}</tbody></table></div></section></>;
}

function PartnerCompliance({ role }: { role: Role }) {
  return <><section className="compliance-score"><div><strong>96</strong><span>/100</span></div><p><small>COMPLIANCE SCORE</small><h2>Bisnis siap beroperasi</h2><em>1 dokumen akan kedaluwarsa dalam 30 hari.</em></p><ActionButton message="Panduan compliance dibuka">Lihat standar Ruvana</ActionButton></section><div className="compliance-grid">{[["Legalitas bisnis","NIB, NPWP, akta perusahaan","Verified","18 Agu 2027"],["Perizinan operasional",`Izin ${role.business.toLowerCase()} dan wilayah operasi`,"Verified","12 Jan 2027"],["Sertifikasi keselamatan","SOP, checklist, dan bukti pelatihan","Expiring","22 Okt 2026"],["Asuransi tanggung gugat","Polis public liability","Verified","30 Jun 2027"],["Rekening & beneficial owner","KYC dan verifikasi payout","Verified","—"],["Standar kualitas Ruvana","Audit layanan dan mystery review","Passed","15 Sep 2026"]].map((row) => <article className="panel" key={row[0]}><header><span><FileCheck2 size={20} /></span><b>{row[2]}</b></header><strong>{row[0]}</strong><p>{row[1]}</p><footer><small>Berlaku hingga</small><span>{row[3]}</span><ActionButton message={`Dokumen ${row[0]} dibuka`} className="icon-action"><ChevronRight size={16} /></ActionButton></footer></article>)}</div></>;
}

function PartnerInbox() {
  return <section className="partner-inbox panel"><aside><div><Search size={17} /><input placeholder="Cari percakapan" /></div>{[["TA","Traveler Demo A","DEMO-ORDER-A","Saya tiba 15 menit lebih awal","2m"],["TB","Traveler Demo B","DEMO-ORDER-B","Bisa bantu ubah jumlah peserta?","12m"],["RC","Ruvana Care","DEMO-CASE-A","Dokumen contoh telah diverifikasi","28m"],["TC","Traveler Demo C","DEMO-ORDER-C","Terima kasih informasinya","1h"]].map((row,index) => <button className={index===0?"is-active":""} key={row[2]}><span>{row[0]}</span><p><strong>{row[1]}</strong><small>{row[2]}</small><em>{row[3]}</em></p><time>{row[4]}</time></button>)}</aside><div className="partner-chat"><header><span>TA</span><p><strong>Traveler Demo A</strong><small>Pesanan simulasi · layanan hari ini</small></p><ActionButton message="Detail booking dibuka">Booking detail</ActionButton></header><div><p className="is-guest">Halo, saya tiba sekitar 15 menit lebih awal. Apakah bisa langsung registrasi?<small>18.31</small></p><p className="is-partner">Halo Kak, tentu. Tim kami sudah menerima informasi dan area tunggu tersedia. Silakan tunjukkan QR voucher saat tiba.<small>18.33 · Read</small></p><p className="is-guest">Baik, terima kasih.<small>18.34</small></p></div><footer><ActionButton message="Lampiran dipilih">+</ActionButton><input placeholder="Tulis balasan..." /><ActionButton variant="primary" message="Pesan simulasi terkirim">Kirim</ActionButton></footer></div></section>;
}

function PartnerSettings({ role }: { role: Role }) {
  return <div className="partner-settings"><section className="panel"><header className="panel__header"><div><h2>Profil bisnis</h2><p>Form contoh untuk informasi publik dan kontak operasional.</p></div></header><div className="form-grid"><label>Nama bisnis<input defaultValue={`${role.business} Partner Demo`} /></label><label>Jenis bisnis<input defaultValue={role.name} /></label><label>Email operasional<input placeholder="Masukkan email bisnis" /></label><label>Nomor bantuan<input placeholder="Masukkan nomor bantuan" /></label><label className="form-grid__full">Alamat kantor<textarea placeholder="Masukkan alamat bisnis" /></label></div><ActionButton variant="primary" message="Profil bisnis disimpan">Simpan profil</ActionButton></section><section className="panel"><header className="panel__header"><div><h2>Integrasi & API</h2><p>Hubungkan sistem operasional yang sudah digunakan.</p></div></header><div className="integration-list">{[["Ruvana Inventory API","Sinkronisasi produk, harga, dan kapasitas","Connected"],["Webhook booking","Notifikasi booking dan perubahan status","Connected"],["Accounting connector","Settlement ke software akuntansi","Setup"],["Tracking provider","Lokasi armada atau aktivitas","Connected"]].map((row) => <div key={row[0]}><span><Link2 size={19} /></span><p><strong>{row[0]}</strong><small>{row[1]}</small></p><b>{row[2]}</b><ActionButton message={`Pengaturan ${row[0]} dibuka`}>Kelola</ActionButton></div>)}</div></section><section className="panel"><header className="panel__header"><div><h2>Kebijakan pelanggan</h2><p>Pembatalan, perubahan jadwal, no-show, dan refund.</p></div></header><div className="settings-cards"><button><strong>Kebijakan fleksibel</strong><span>Refund penuh H-3, 50% sampai H-1</span><Check size={17} /></button><button><strong>Perubahan jadwal</strong><span>1x perubahan tanpa biaya hingga H-2</span><ChevronRight size={17} /></button><button><strong>No-show protection</strong><span>Klaim sesuai bukti kejadian pelanggan</span><ChevronRight size={17} /></button></div></section></div>;
}
