"use client";

import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, CreditCard, Landmark, LockKeyhole, QrCode, ShieldCheck, TicketPercent, WalletCards } from "lucide-react";
import { useState } from "react";
import { PlatformIcon } from "@/components/platform-icon";
import type { EcosystemProduct } from "@/lib/ecosystem";

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const methods = [["va","Virtual Account","BCA, Mandiri, BNI, BRI",Landmark],["qris","QRIS","Semua aplikasi pembayaran",QrCode],["card","Kartu debit / kredit","Visa, Mastercard, JCB",CreditCard],["wallet","Nusavyra Wallet","Saldo Rp2.450.000",WalletCards]] as const;

export function ServiceCheckoutFlow({ product }: { product: EcosystemProduct }) {
  const [step,setStep]=useState(1);
  const [method,setMethod]=useState("va");
  const [insurance,setInsurance]=useState(product.category === "aviation" || product.category === "marine");
  const [promo,setPromo]=useState(false);
  const serviceFee=Math.max(5000,Math.round(product.price*.035));
  const protection=insurance?Math.max(45000,Math.round(product.price*.012)):0;
  const discount=promo?Math.min(250000,Math.round(product.price*.06)):0;
  const total=product.price+serviceFee+protection-discount;

  if(step===3) return <section className="checkout-success"><span><Check size={31}/></span><small>PESANAN TERKONFIRMASI</small><h1>{product.title} siap digunakan</h1><p>Pembayaran dummy sebesar <strong>{rupiah.format(total)}</strong> berhasil. Voucher, invoice, dan petunjuk layanan sudah masuk ke perjalanan Anda.</p><div className="success-code"><span>ORDER ID</span><strong>NSV-260927-8F31</strong></div><div className="success-timeline"><div className="is-done"><span><Check size={14}/></span><p><strong>Pembayaran diterima</strong><small>27 Sep 2026 · 19.48 WIB</small></p></div><div><span>2</span><p><strong>Voucher diterbitkan</strong><small>Otomatis setelah konfirmasi</small></p></div><div><span>3</span><p><strong>Masuk ke itinerary</strong><small>Bali Escape</small></p></div></div><div className="checkout-success__actions"><Link className="button button--primary" href="/account/orders">Buka pesanan <ArrowRight size={17}/></Link><Link className="button button--secondary" href="/account/trips">Lihat itinerary</Link></div></section>;

  return <div className="checkout-shell"><div className="checkout-main"><Link className="back-link" href={`/explore/${product.category}/${product.id}`}><ArrowLeft size={16}/>Kembali ke detail layanan</Link><div className="checkout-title"><span className="eyebrow">ONE JOURNEY CHECKOUT</span><h1>{step===1?"Tinjau pesanan Anda":"Pilih pembayaran"}</h1><p>{step===1?"Detail layanan, traveler, add-on, dan proteksi berada dalam satu ringkasan.":"Harga dikunci selama 15 menit."}</p></div><div className="stepper">{["Detail","Pembayaran","Selesai"].map((label,index)=><div className={step>=index+1?"is-active":""} key={label}><span>{step>index+1?<Check size={14}/>:index+1}</span><strong>{label}</strong></div>)}</div>
    {step===1?<div className="checkout-sections"><section><h2>Detail layanan</h2><div className="service-checkout-detail"><span><PlatformIcon name={product.icon} size={24}/></span><p><small>{product.provider}</small><strong>{product.title}</strong><em>{product.schedule} · {product.location}</em></p><button onClick={()=>window.alert("Pemilih jadwal dummy dibuka.")}>Ubah</button></div></section><section><h2>Data pemesan</h2><div className="form-grid"><label>Nama lengkap<input placeholder="Masukkan nama pemesan"/></label><label>Nomor WhatsApp<input placeholder="Masukkan nomor aktif"/></label><label>Email voucher<input placeholder="Masukkan email voucher"/></label><label>Jumlah peserta<select defaultValue="1"><option value="1">1 peserta</option><option value="2">2 peserta</option><option value="3">3 peserta</option></select></label></div></section><section className={`protection-option ${insurance?"is-active":""}`}><span><ShieldCheck size={22}/></span><div><h2>Nusavyra Travel Protection</h2><p>Perlindungan pembatalan, kecelakaan, dan bantuan darurat sesuai layanan.</p><strong>+ {rupiah.format(Math.max(45000,Math.round(product.price*.012)))}</strong></div><button onClick={()=>setInsurance((value)=>!value)}>{insurance?"Ditambahkan":"Tambahkan"}</button></section></div>:null}
    {step===2?<div className="checkout-sections"><section><h2>Metode pembayaran</h2><div className="payment-methods">{methods.map(([id,label,note,Icon])=><button className={method===id?"is-active":""} key={id} onClick={()=>setMethod(id)}><span><Icon size={20}/></span><p><strong>{label}</strong><small>{note}</small></p><i>{method===id?<Check size={13}/>:null}</i></button>)}</div></section><label className="terms-check"><input type="checkbox" defaultChecked/><span>Saya menyetujui jadwal, kebijakan perubahan, pembatalan, ketentuan operator, dan syarat penggunaan Nusavyra.</span></label></div>:null}<div className="checkout-nav">{step===2?<button className="button button--secondary" onClick={()=>setStep(1)}><ArrowLeft size={16}/>Kembali</button>:<span/>}<button className="button button--primary" onClick={()=>setStep(step===1?2:3)}>{step===1?"Lanjut ke pembayaran":`Bayar ${rupiah.format(total)}`}<ArrowRight size={17}/></button></div></div>
    <aside className="checkout-summary checkout-service-summary"><div className="checkout-service"><span><PlatformIcon name={product.icon} size={30}/></span><p><small>{product.badge}</small><strong>{product.title}</strong><em>{product.provider}</em></p></div><div className="summary-line"><span>Harga layanan</span><strong>{rupiah.format(product.price)}</strong></div><div className="summary-line"><span>Biaya layanan</span><strong>{rupiah.format(serviceFee)}</strong></div>{insurance?<div className="summary-line"><span>Travel Protection</span><strong>{rupiah.format(protection)}</strong></div>:null}{promo?<div className="summary-line summary-line--discount"><span>Promo JOURNEY6</span><strong>−{rupiah.format(discount)}</strong></div>:null}<div className="promo-input"><TicketPercent size={17}/><input placeholder="Kode promo" defaultValue={promo?"JOURNEY6":""}/><button onClick={()=>setPromo(true)}>Pakai</button></div><div className="summary-total"><span>Total pembayaran</span><strong>{rupiah.format(total)}</strong></div><p className="secure-payment"><LockKeyhole size={15}/>Pembayaran terenkripsi dan terlindungi.</p></aside></div>;
}
